-- Nota operativa per il caricamento manuale delle anagrafiche in VoltDB.
--
-- Questo file non viene eseguito automaticamente da sqlcmd: contiene i comandi
-- csvloader equivalenti a quelli gia' usati dal servizio voltdb-init in
-- docker-compose.yml.
--
-- Per un caricamento manuale, eseguire questi comandi dentro il container
-- fraud-voltdb:
--
-- docker exec -it fraud-voltdb bash
--
-- csvloader customers --file /data/customers.csv --skip 1
-- csvloader cards --file /data/cards.csv --skip 1
-- csvloader merchants --file /data/merchants.csv --skip 1
--
-- Verifica:
--
-- sqlcmd
-- SELECT COUNT(*) FROM customers;
-- SELECT COUNT(*) FROM cards;
-- SELECT COUNT(*) FROM merchants;
